# Generated by Django 4.1.13 on 2024-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_list', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Keywords Config',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
