# Generated by Django 4.1.13 on 2024-04-05 08:09

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp_list', '0003_keywordsconfig_delete_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeywordsConfig',
        ),
        migrations.CreateModel(
            name='KeywordUploadProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Keyword Upload',
                'verbose_name_plural': 'Keyword Uploads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
