# Generated by Django 4.1.13 on 2024-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_list', '0004_delete_keywordsconfig_keyworduploadproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.TextField()),
            ],
        ),
    ]
